### ISSUE TITLE
Error: Cannot find module 'mongodb/node_modules/bson'

### ISSUE THREAD

**Issue by fresh5447** [scotch-io/react-tweets#15]
Node sure if this is an NPM issue or app issue. After following steps of cloning, npm installing, and updating Twitter Credentials.. This is the error I get when I type `node server.js`

module.js:333
    throw err;
          ^
Error: Cannot find module 'mongodb/node_modules/bson'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/Users/Douglas/code/twitter-streamer/node_modules/mongoose/lib/drivers/node-mongodb-native/objectid.js:8:16)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)

**Comment by fresh5447** [comment]
After deleting node_modules and reinstalling a couple times it still didn't work. I finally manually npm installed `bson` and this fixed the issue. I think this was an NPM issue not an App issue, but still wanted to note it if anyone else has the same problem.

**Comment by parth0595** [comment]
yeah i had the same issue and i am trying to update the code on 

> Heroku.

 I am able to make it work with 
npm install inside node modules/mongodb but I am unable to do so in the server code while deploying it on heroku.
