### ISSUE TITLE
I can't seem to run the project

### ISSUE THREAD

**Issue by lifeiscontent** [scotch-io/react-tweets#8]
I've done all the required steps in the readme.

but when I run `node server.js` I get the following errors:

``` bash
react-tweets (master) $ node server.js
Express server listening on port 8080

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at EventEmitter.emit (events.js:74:15)
    at ClientRequest.<anonymous> (/Users/lifeiscontent/Workspace/Javascript/react-tweets/node_modules/ntwitter/lib/twitter.js:251:14)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1693:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1588:20)
    at CleartextStream.read [as _read] (tls.js:514:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
react-tweets (master) $
```

**Comment by lifeiscontent** [comment]
nevermind, I just forgot the API keys.
